### ISSUE TITLE
Performance comparison to in-memory gemm

### ISSUE THREAD

**Issue by hoseung2** [SKKU-ESLAB/CNN-on-flash#11]
I've checked your response to the last issue about evaluation. 

You plotted memory usages and inference times of only on-flash GEMM, but not in-memory GEMM.

It will be meaningful to compare the execution time between in-memory and on-flash GEMM.

**Comment by GH-Jo** [comment]
I ran in-mem gemm with matrices of the same size as used in on-flash gemm example in README, 
The execution time of in-mem gemm with inputs and output matrices of 4096x4096 is 20ms.
Compared to on-flash gemm, it is more than 100 times faster.
