### ISSUE TITLE
Peak memory usage

### ISSUE THREAD

**Issue by hoseung2** [SKKU-ESLAB/CNN-on-flash#5]
Hi,
I want to see memory usage when performing GEMM operation using CNN-on-flash.

How can I print out this?

**Comment by GH-Jo** [comment]
You can set on debug option when you do cmake with the following command
> cmake -DCMAKE_BUILD_TYPE=Debug ..

Then you will see debug messages when you execute gemm.
Among them, _commit_size_ means the allocated total memory of matrix tiles at the moment. 

I just now added several code lines to print the maximum of allocated memory of matrices at the end of execution. Please check it.

Also, If you want to know the total memory usage of the process, I recommend to use  https://github.com/LeeHayun/rss_watch .
